# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-04 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='moment',
            name='kind',
            field=models.CharField(choices=[('Python\u6280\u672f', 'Python\u6280\u672f2'), ('\u6570\u636e\u5e93\u6280\u672f', '\u6570\u636e\u5e93\u6280\u672f2'), ('\u7ecf\u6d4e\u5b66', '\u7ecf\u6d4e\u5b662'), ('\u6587\u4f53\u8d44\u8baf', '\u6587\u4f53\u8d44\u8baf2'), ('\u4e2a\u4eba\u5fc3\u60c5', '\u4e2a\u4eba\u5fc3\u60c52'), ('\u5176\u5b83', '\u5176\u5b832')], default=('Python\u6280\u672f', 'Python\u6280\u672f2'), max_length=20),
        ),
        migrations.AlterField(
            model_name='moment',
            name='user_name',
            field=models.CharField(default='\u533f\u540d', max_length=20),
        ),
    ]
